server:
  port: 8081
  servlet:
    context-path: '/culinary-user-service/'

spring:
  application:
    name: CulinaryApi-User-Service
  datasource:
    url: jdbc:postgresql://postgres-db-user-service:5432/Culinary-user-service
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://gxfhiqck:3sivG1zlLvv3W7SWQcK14y010juFScxm@leopard.lmq.cloudamqp.com/gxfhiqck

Culinary:
  broker:
    exchange:
      userEventExchange: Culinary.userEvent
      userServiceEventExchange: Culinary.userServiceEvent
    queue:
      userEventQueue:
        name: Culinary.userEvent.userService
  auth:
    jwt-secret: ZHsOVU5Y6gGU3/S9WZfY5W/Ni6ZixK0I9rZ44MudSRuNYvib+ZoeP/YQNfEvXlDhEgV60Ma8csbcv6ALfOjdyMg==
