server:
  port: 8085
  servlet:
    context-path: '/culinary-delivery-service/'

spring:
  application:
    name: CulinaryApi-delivery-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/Culinary-delivery
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://gxfhiqck:3sivG1zlLvv3W7SWQcK14y010juFScxm@leopard.lmq.cloudamqp.com/gxfhiqck


Culinary:
  broker:
    exchange:
      deliverymanEventExchange: Culinary.deliverymanEvent
      deliveryEventExchange: Culinary.deliveryEvent
      orderServiceEventExchange: Culinary.OrderService
    queue:
      deliverymanEventQueue:
        name: Culinary.deliverymanEvent.Deliveryman
      deliveryEventQueue:
        name: culinary.deliveryEvent.delivery

  auth:
    jwt-secret: ZHsOVU5Y6gGU3/S9WZfY5W/Ni6ZixK0I9rZ44MudSRuNYvib+ZoeP/YQNfEvXlDhEgV60Ma8csbcv6ALfOjdyMg==
