server:
  port: 8080

spring:
  application:
    name: CulinaryApi-gatewey-service
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://CULINARYAPI-AUTHUSER-SERVICE
          predicates:
            - Path=/culinary-authuser/**

        - id: user-service
          uri: lb://CULINARYAPI-USERSERVICE
          predicates:
            - Path=/culinary-user-service/**

        - id: menu-service
          uri: lb://CULINARYPI-MENU-SERVICE
          predicates:
            - Path=/culinary-menu-service/**

        - id: delivery-service
          uri: lb://CULINARYAPI-DELIVERY-SERVICE
          predicates:
            - Path=/culinary-delivery-service/**

        - id: order-service
          uri: http://localhost:8089/
          predicates:
            - Path=/culinary-order-service/**
