server:
  port: 8087
  servlet:
    context-path: '/culinary-menu-service/'

spring:
  application:
    name: CulinaryApi-Menu-Service
  datasource:
    url:  jdbc:postgresql://postgres-db-menuservice:5432/Culinaryapi-MenuService
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://gxfhiqck:3sivG1zlLvv3W7SWQcK14y010juFScxm@leopard.lmq.cloudamqp.com/gxfhiqck

Culinary:
  broker:
    exchange:
      menuEventExchange: Culinary.MenuService
  auth:
    jwt-secret: ZHsOVU5Y6gGU3/S9WZfY5W/Ni6ZixK0I9rZ44MudSRuNYvib+ZoeP/YQNfEvXlDhEgV60Ma8csbcv6ALfOjdyMg==