server:
  port: 8082
  servlet:
    context-path: '/culinary-authuser/'

spring:
  application:
    name: CulinaryApi-authuser-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/Culinary-authuser
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://gxfhiqck:3sivG1zlLvv3W7SWQcK14y010juFScxm@leopard.lmq.cloudamqp.com/gxfhiqck


Culinary:
  broker:
    exchange:
      userEventExchange: Culinary.userEvent
      deliverymanEventExchange: Culinary.deliverymanEvent

  auth:
    jwt-secret: ZHsOVU5Y6gGU3/S9WZfY5W/Ni6ZixK0I9rZ44MudSRuNYvib+ZoeP/YQNfEvXlDhEgV60Ma8csbcv6ALfOjdyMg==
    jwt-expiration-ms: 360000000